# Generated by Django 6.0.3 on 2026-04-03 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (must be positive).', max_digits=12)),
                ('record_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], help_text='income or expense.', max_length=7)),
                ('category', models.CharField(help_text='Category label, e.g. salary, utilities, marketing.', max_length=50)),
                ('date', models.DateField(help_text='Date of the transaction.')),
                ('description', models.TextField(blank=True, default='', help_text='Optional notes or description.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Record approval status.', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this record.', on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
